# 分析报告的主体结构
head:
  title: "零售业务关键指标月度监测报告"
  data_dt: "2024-12-31"
  org_name: "贵阳 南宁"
  author: "零售金融部"

sections:
  # - section_title: "0 引言"
  #   content: "> 量：规模筑基，驱动发展势能。量作为业务发展的基本盘，聚焦规模增长与市场渗透。\n> 价：定价中枢，把控价值命脉。定价能力是零售银行经营智慧的核心体现。\n> 质：结构优化，筑牢风险堤坝。质量维度是业务可持续发展的压舱石。\n> 客：经营本源，激活增长引擎。客户获取与提升是业务发展的源头活水。\n> 效：价值归宿，检验战略成色。效益维度是检验业务经营成效的核心标尺。\n> \n> 本报告构建\"量、价、质、客、效\"分析框架，系统解构零售业务发展脉络，为经营决策提供全景式洞察。在指标分析过程中，运用四比方法，通过比自身（同比、环比）、比预算（计划完成率）、比同组（小组内排名）、比市场（同业排名），诊断经营机构零售业务发展情况，最后根据指标变动总结经营机构的经营亮点与不足。"
  # - section_title: "业务发展亮点与不足总结"
  #   content: "XXX"
  - section_title: "1 规模"
    sections:
      - section_title: "1.1 负债业务"
        sections:
          - section_title: "1.1.1 存款"
            indicators:
              - name: "全口径个人存款时点余额"
                note: "（亿元）"
                operators:
                  - "当期值: XX"
                  - "组内排名: XX"
                  - "近期趋势: XX"
                  - "同比: XX"
                  - "环比: XX"
              - name: "全口径个人存款时点余额年增量"
                note: "（亿元）"
                operators:
                  - "当期值: XX"
                  - "组内排名: XX"
                  # - "近期趋势: XX"
                  - "同比: XX"
                  # - "环比: XX"
      - section_title: "1.2 资产业务"
        sections:
          - section_title: "1.2.1 个人贷款"
            indicators:
              - name: "个人贷款余额"
                note: "（亿元）"
                operators:
                  - "当期值: XX"
                  - "组内排名: XX"
                  - "近期趋势: XX"
                  - "同比: XX"
                  - "环比: XX"
              - name: "个人贷款余额年增量"
                note: "（亿元）"
                operators:
                  - "当期值: XX"
                  - "组内排名: XX"
                  # - "近期趋势: XX"
                  - "同比: XX"
                  # - "环比: XX"

  - section_title: "附录"
    sections:
      - section_title: "主要指标组内排名"
        indicator_rank: ""